preparations for first release

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -7,25 +7,25 @@ name: CI
 on: [push, pull_request]
 
 jobs:
-  uptodate:
-    name: Node test build
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-node@v3
-        with:
-          node-version: "16"
-          cache: "npm"
-      - run: npm install
-      - run: npm run build
-      - name: Check for differences between commit and built file
-        run: |
-          if ! git diff --exit-code; then
-            echo '::error::There are differences between commit and code built. Make sure that `npm run build` is run before commiting. Check log for more details.'
-            git diff
-            exit 1
-          fi
-        shell: bash
+  # uptodate:
+  #   name: Node test build
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - uses: actions/setup-node@v3
+  #       with:
+  #         node-version: "16"
+  #         cache: "npm"
+  #     - run: npm install
+  #     - run: npm run build
+  #     - name: Check for differences between commit and built file
+  #       run: |
+  #         if ! git diff --exit-code; then
+  #           echo '::error::There are differences between commit and code built. Make sure that `npm run build` is run before commiting. Check log for more details.'
+  #           git diff
+  #           exit 1
+  #         fi
+  #       shell: bash
 
   tests:
     strategy:
@@ -40,6 +40,7 @@ jobs:
           node-version: "16"
           cache: "npm"
       - run: npm install
+      - run: npm run build
       - name: Run test suite
         run: |
           if [[ "$RUNNER_OS" == macOS ]]; then
@@ -50,6 +51,9 @@ jobs:
 
           npm test
         shell: bash
+      - name: Test parsing sample Nim files
+        run: npm exec tree-sitter parse -s -t -q 'samples/**/*.nim'
+        shell: bash
 
   rust:
     strategy:
@@ -59,6 +63,12 @@ jobs:
     name: Run rust test build on ${{ matrix.os }}
     steps:
       - uses: actions/checkout@v3
+      - uses: actions/setup-node@v3
+        with:
+          node-version: "16"
+          cache: "npm"
+      - run: npm install
+      - run: npm run build
       - name: Install Rust toolchain
         uses: actions-rs/toolchain@v1
         with:
